from __future__ import annotations

from datetime import date
from typing import Protocol

from habit_tracker.domain.entities.completion import Completion
from habit_tracker.domain.entities.habit import Habit
from habit_tracker.domain.entities.user import User
from habit_tracker.domain.value_objects.habit_name import HabitName
from habit_tracker.domain.value_objects.telegram_id import TelegramId


class UserRepository(Protocol):
    async def save(self, user: User) -> User: ...
    async def find_by_telegram_id(self, telegram_id: TelegramId) -> User | None: ...


class HabitRepository(Protocol):
    async def save(self, habit: Habit) -> Habit: ...
    async def find_by_id(self, habit_id: int) -> Habit | None: ...
    async def find_active_by_user(self, user_id: int) -> list[Habit]: ...
    async def find_active_by_user_and_name(self, user_id: int, name: HabitName) -> Habit | None: ...
    async def delete(self, habit_id: int) -> None: ...


class CompletionRepository(Protocol):
    async def save(self, completion: Completion) -> Completion: ...
    async def find_today_by_habits(self, habit_ids: list[int]) -> list[Completion]: ...
    async def get_completion_dates(self, habit_id: int) -> list[date]: ...

    # The batch variants exist because their per-habit equivalents were called
    # in a loop, turning one screen of habits into one query per habit. Both
    # return an entry for every requested ID, so callers never need a default.
    async def get_completion_dates_by_habits(self, habit_ids: list[int]) -> dict[int, list[date]]: ...
    async def find_by_habits_since(self, habit_ids: list[int], since: date) -> dict[int, list[Completion]]: ...
